"""Generate the compact thesis workflow figure from verified repository paths."""
from pathlib import Path

SCRIPTS = [
    'src/accidents/match_weather.py',
    'src/traffic/monthly_vkt.py',
    'src/analysis/oe_analysis.py',
    'src/tables/traffic_corrected_oe.py',
    'src/tables/monthly_vkt_rate.py',
]


def generate(output=Path('reports/thesis')):
    output.mkdir(parents=True, exist_ok=True)
    for path in SCRIPTS:
        if '__main__' not in Path(path).read_text():
            raise ValueError(f'No module entry point: {path}')
    for path in ('src/thesis_pipeline.py', 'src/validate.py'):
        if not Path(path).is_file():
            raise FileNotFoundError(path)
    # Retain the tracked legacy output as an explicit empty stub, not a table.
    (output/'pipeline_analysis.tex').write_text('% Retired analysis-summary table; see Section 3.3.\n')
    figure = r'''% Generated by src.tables.pipeline; paths verified against current sources.
\begin{figure}[H]
\centering
\begin{tikzpicture}[node distance=4mm,
  stage/.style={draw, line width=0.4pt, text width=11.5cm, align=center,
                inner sep=4pt, font=\small}]
\node[stage] (source) {Institutional source deliveries\\Register extracts and documentation; weather; roads and traffic; boundaries};
\node[stage, below=of source] (clean) {Cleaning and standardisation\\Identifiers, dates, coordinates, injury codes and weather validity};
\node[stage, below=of clean] (link) {Spatial and temporal linkage; exposure construction\\Accident-time weather; station--season frequencies\\Counter response; monthly-frequency VKT};
\node[stage, below=of link] (analysis) {Three retained analyses\\Weather-frequency O/E\\approximate traffic-corrected O/E\\monthly-frequency VKT};
\node[stage, below=of analysis] (products) {Generated tables, figures and LaTeX fragments\\Automated numerical validation and consistency checks};
\draw[->] (source) -- (clean);
\draw[->] (clean) -- (link);
\draw[->] (link) -- (analysis);
\draw[->] (analysis) -- (products);
\end{tikzpicture}
\caption[Reproducible data and analysis workflow.]{Reproducible data and analysis workflow.}
\label{fig:reproducible-workflow}
\end{figure}
'''
    (output/'pipeline_prepare.tex').write_text(figure)


if __name__ == '__main__':
    generate()
